Upgrade OutsideURLAuthoring to Angular component
WISE-Community/WISE pull request #2871
Opened 2021-01-08 20:56 UTC by geoffreykwan

Make sure Outside URL authoring still works.

Closes #2763

2021-01-11 22:32 UTC, hirokiterashima requested changes
Behavior looks good.

I made few code improvement suggestions for outside-url-authoring.component.ts. Let me know what you think.

Also, it looks like you forgot to extract i18n strings (messages.xlf)?

2021-01-11 22:32 UTC, hirokiterashima commented on src/main/webapp/wise5/components/outsideURL/outside-url-authoring/outside-url-authoring.component.ts
> +    this.selectedSubjects = [];
Move these to class variable?

2021-01-11 22:32 UTC, hirokiterashima commented on src/main/webapp/wise5/components/outsideURL/outside-url-authoring/outside-url-authoring.component.ts
> +        a.metadata.title > b.metadata.title ? 1 : -1
```suggestion
        a.metadata.title.localeCompare(b.metadata.title)
```

2021-01-11 22:32 UTC, hirokiterashima commented on src/main/webapp/wise5/components/outsideURL/outside-url-authoring/outside-url-authoring.component.ts
> +      .subscribe((width: string) => {
```suggestion
      .subscribe(() => {
```

2021-01-11 22:32 UTC, hirokiterashima commented on src/main/webapp/wise5/components/outsideURL/outside-url-authoring/outside-url-authoring.component.ts
> +      .subscribe((height: string) => {
```suggestion
      .subscribe(() => {
```

2021-01-11 22:32 UTC, hirokiterashima commented on src/main/webapp/wise5/components/outsideURL/outside-url-authoring/outside-url-authoring.component.ts
> +      }
This logic was a bit difficult to follow for me because of the negation and the order in which it's testing things. What do you think about re-writing it like this?
```suggestion
      if (this.isAnySubjectChosen()) {
        return (
          this.isSubjectMatch(this.selectedSubjects, oer) &&
          this.isTextMatch(this.searchText, JSON.stringify(oer))
        );
      }
      return this.isTextMatch(this.searchText, JSON.stringify(oer));
```

2021-01-11 22:32 UTC, hirokiterashima commented on src/main/webapp/wise5/components/outsideURL/outside-url-authoring/outside-url-authoring.component.ts
> +    return testText.toLowerCase().indexOf(searchText.toLowerCase()) !== -1;
```suggestion
    return testText.toLowerCase().includes(searchText.toLowerCase());
```

2021-01-12 17:23 UTC, geoffreykwan commented
Ok, I cleaned up the code and ran the i18n translation generation.

2021-01-12 18:15 UTC, hirokiterashima approved these changes

2021-01-12 18:18 UTC, hirokiterashima commented
Looks good. There are new duplication issues now that OutsideURLAuthoring and HTMLAuthoring have both been converted to Angular and their structures are similar: https://codeclimate.com/github/WISE-Community/WISE/pull/2871#issues. We should look into these soon.

2021-01-12 20:50 UTC, breity approved these changes
Looks good. 👍

2021-01-12 20:50 UTC, merged