Upgrade Table authoring to Angular component
WISE-Community/WISE pull request #2907
Opened 2021-01-27 20:07 UTC by geoffreykwan

Make sure Table authoring still works.

Closes #2902

2021-01-28 18:42 UTC, hirokiterashima requested changes
Functionality looks good. I cleaned up the code a little bit. Also found a part of the code where I wasn't sure if the null-check is necessary and added comments inline. Can you take a look?

2021-01-28 18:42 UTC, hirokiterashima commented on src/main/webapp/wise5/components/table/table-authoring/table-authoring.component.ts
> +    }
Is this null check necessary?

2021-01-28 18:42 UTC, hirokiterashima commented on src/main/webapp/wise5/components/table/table-authoring/table-authoring.component.ts
> +      }
Is this null check necessary?

2021-01-29 20:04 UTC, geoffreykwan commented
@hirokiterashima Ok I removed those null checks because they didn't seem to be needed. I also set the min value for inputs to 1 and changed some variable names.

2021-01-29 22:17 UTC, hirokiterashima approved these changes
Looks good.

2021-01-29 22:17 UTC, merged